blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('', views.index),
    path('', views.PostList.as_view()),
    # path('<int:pk>/', views.post_detail),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('category/<str:slug>/', views.PostListByCategory.as_view()),
    path('search/', views.Search.as_view()),
    path('search/<str:question>/', views.PostSearch.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)








blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(blank=True)

    # slug : url에 텍스트 주소가 있어도 인식되도록 함
    slug = models.SlugField(unique=False, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/blog/category/{}'.format(self.slug)

    class Meta:
        verbose_name_plural = "categories"


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    # 이미지 필드 추가
    head_image = models.ImageField(upload_to='blog/%Y/%m/%d/', blank=True)

    created = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '{} :: {}'.format(self.title, self.author)

    def get_absolute_url(self):
        return '/blog/{}/'.format(self.pk)

    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)


class SearchList(models.Model):
    searchword = models.CharField(max_length=100)
    data = models.DateTimeField(auto_now_add=True) #현재 시간으로 자동으로 설정

    def __str__(self):
        return self.searchword







blog/views.py
from django.shortcuts import render
from .models import Post, Category, SearchList
from django.views.generic import ListView, DetailView
from django.db.models import Q


# Create your views here.
# [CBV : Class Based View] --------------------------------
class Search(ListView):
    model = SearchList

    def get_queryset(self):
        lt = SearchList.objects.order_by('-data')
        print('searchList >>', lt)

        return lt


class PostList(ListView):
    model = Post

    #작성일 기준으로 내림차순 정렬(최신글)
    def get_queryset(self):
        return Post.objects.order_by('-created')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        print('context 1) : **kwargs >> ', context)

        context['category_list'] = Category.objects.all()
        context['post_without_category'] = Post.objects.filter(category=None).count()
        print('context 2) >> ', context)

        return context


class PostSearch(PostList):
    def get_queryset(self):
        q = self.kwargs['question']
        object_list = Post.objects.filter(Q(title__contains=q) | Q(content__contains=q))
        return object_list
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        context['search_info'] = 'Search Result >> {}'.format(self.kwargs['question'])

        s = SearchList(searchword=self.kwargs['question'])
        s.save()

        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)

        context['category_list'] = Category.objects.all()
        context['post_without_category'] = Post.objects.filter(category=None).count()

        return context


class PostListByCategory(PostList):
    def get_queryset(self):
        slug = self.kwargs['slug']
        print('slug >>', slug)

        category = Category.objects.get(slug=slug)

        return Post.objects.filter(category=category).order_by('-created')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostListByCategory, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        context['post_without_category'] = Post.objects.filter(category=None).count()

        slug = self.kwargs['slug']
        category = Category.objects.get(slug=slug)

        return context


# [FBV : Function Based View] --------------------------------
# def post_detail(request, pk):
#     blog_post = Post.objects.get(pk=pk)
#     context = {
#         'blog_post': blog_post,
#     }
#
#     return render(request, 'blog/post_detail.html', context)


# def index(request):
#     post = Post.objects.all()
#     context = {
#         'post': post,
#     }
#
#     return render(request, 'blog/index.html', context)
#
# -------------------------------------------------------------


blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}BLOG {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '_assets/css/custom.min.css' %}">
</head>
<body>
<!-- 네비게이션 바 시작 -->
<div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
    <div class="container">
        <a href="../" class="navbar-brand">Lab.Python&Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Themes <span
                            class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="themes">
                        <a class="dropdown-item" href="../default/">Default</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="../cerulean/">Cerulean</a>
                        <a class="dropdown-item" href="../cosmo/">Cosmo</a>
                        <a class="dropdown-item" href="../cyborg/">Cyborg</a>
                        <a class="dropdown-item" href="../darkly/">Darkly</a>
                        <a class="dropdown-item" href="../flatly/">Flatly</a>
                        <a class="dropdown-item" href="../journal/">Journal</a>
                        <a class="dropdown-item" href="../litera/">Litera</a>
                        <a class="dropdown-item" href="../lumen/">Lumen</a>
                        <a class="dropdown-item" href="../lux/">Lux</a>
                        <a class="dropdown-item" href="../materia/">Materia</a>
                        <a class="dropdown-item" href="../minty/">Minty</a>
                        <a class="dropdown-item" href="../pulse/">Pulse</a>
                        <a class="dropdown-item" href="../sandstone/">Sandstone</a>
                        <a class="dropdown-item" href="../simplex/">Simplex</a>
                        <a class="dropdown-item" href="../sketchy/">Sketchy</a>
                        <a class="dropdown-item" href="../slate/">Slate</a>
                        <a class="dropdown-item" href="../solar/">Solar</a>
                        <a class="dropdown-item" href="../spacelab/">Spacelab</a>
                        <a class="dropdown-item" href="../superhero/">Superhero</a>
                        <a class="dropdown-item" href="../united/">United</a>
                        <a class="dropdown-item" href="../yeti/">Yeti</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blog/">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact/">Contact</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Simplex <span
                            class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="download">
                        <a class="dropdown-item" rel="noopener" target="_blank"
                           href="https://jsfiddle.net/bootswatch/3he50zsf/">Open in JSFiddle</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="../4/simplex/bootstrap.min.css" download>bootstrap.min.css</a>
                        <a class="dropdown-item" href="../4/simplex/bootstrap.css" download>bootstrap.css</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="../4/simplex/_variables.scss" download>_variables.scss</a>
                        <a class="dropdown-item" href="../4/simplex/_bootswatch.scss" download>_bootswatch.scss</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- 네비게이션 바 끝 -->

<div class="container">

    <!-- 블로그 코딩 시작 -->
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">

            {% block content %}
            {% endblock %}

        </div>
        <!-- 블로그 코딩 끝 -->


        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Search Widget -->
            <div class="card my-4">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <div class="input-group">
{#                        <input type="text" class="form-control" id="search_input"  placeholder="Search for...">#}
                        <input type="text" class="form-control" id="search_input" onkeyup="enter()" onkeyup="search_enter()" placeholder="Search for...">
                        <span class="input-group-append">
                <button class="btn btn-secondary" type="button" onclick="search_post()">Go!</button>
              </span>
                    </div>
                </div>
            </div>

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">

                                {% for category in category_list %}
                                    <li>
                                        <a href="{{ category.get_absolute_url }}">{{ category.name }}({{ category.post_set.count }})</a>
                                    </li>
                                {% endfor %}
                                <li>
                                    <a href="#">미분류({{ post_without_category }})</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function search_post(){
            var search_value = document.getElementById('search_input').value
            {#alert(search_value)#}
            location.href = '/blog/search/' + search_value + '/';
        }

        function enter(){
            if(window.event.keyCode == 13){
                search_post();
            }
        }
    </script>
    <script src="{% static '_assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '_assets/js/custom.js' %}"></script>
</div>

</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

<title>{% block title %} {{ object.title }} {% endblock %}</title>

{% block content %}

    <!-- Title -->
    <h1 class="mt-4">
        {{ object.title }}
    </h1>

    <!-- Author -->
    <p class="lead">
        by
        <a href="#">{{ object.author }}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p>Posted on {{ object.created }}</p>

    <hr>

    <!-- Preview Image -->
    <img class="img-fluid rounded" src="{{ object.head_image.url }}" alt="">

    <hr>

    <!-- Post Content -->
    <p class="lead">{{ object.content }}</p>

    <hr>

    <!-- Comments Form -->
    <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
            <form>
                <div class="form-group">
                    <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

    <!-- Single Comment -->
    <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio,
            vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec
            lacinia congue felis in faucibus.
        </div>
    </div>

    <!-- Comment with nested comments -->
    <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio,
            vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec
            lacinia congue felis in faucibus.

            <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">Commenter Name</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras
                    purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi
                    vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>

            <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">Commenter Name</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras
                    purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi
                    vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>

        </div>
    </div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1 class="my-4">
        Blog
        {% if search_info %} <small class="text-muted"> : {{ search_info }}({{ object_list.count }})</small> {% endif %}
    </h1>
        {% if search_info %} <small class="text-muted"> {{ search_info }}({{ object_list.count }}) </small>  {% endif %}
    </h1>
    <!-- Blog Post -->
    {% if object_list.exists %}
        {% for p in object_list %}
            <div class="card mb-4">
                {% if p.head_image %}
                    <img class="card-img-top" src="{{ p.head_image.url }}" alt="Card image cap">
                {% else %}
                    <img class="card-img-top" src="https://picsum.photos/id/237/750/300" alt="Card image cap">
                {% endif %}

                <div class="card-body">
                    {% if p.category %}
                        <span class="badge bg-success float-right">{{ p.category }}</span>
                    {% else %}
                        <span class="badge bg-success float-right">미분류</span>
                    {% endif %}
                    <h2 class="card-title"> {{ p.title }}</h2>
                    <p class="card-text"> {{ p.content | truncatewords:50 }}</p>
                    <a href="{{ p.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
                </div>

                <div class="card-footer text-muted">
                    Posted on {{ p.created }} by
                    <a href="#"> {{ p.author }} </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h2>아직 게시물이 없습니다.</h2>
    {% endif %}

{% endblock %}

blog/templates/blog/searchlist_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Good day!!!!</h1>

    object_list : {{ object_list }} <br>
    searchlist_list : {{ searchlist_list }} <br>
    searchlist_list.0 : {{ searchlist_list.0 }} <br>

    <ul>
        {% for search in searchlist_list %}
            <li> {{ search.searchword }} - {{ search.data }} </li>
        {% endfor %}
    </ul>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">순번</th>
            <th scope="col">검색어</th>
            <th scope="col">조회날짜</th>
        </tr>
        </thead>
        <tbody>
        {% for search in searchlist_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ search.searchword }}</td>
            <td>{{ search.data }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}